# Generated by Django 6.0.2 on 2026-04-06 14:08

import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha])),
                ('last_name', models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha])),
                ('age', models.IntegerField(error_messages={'min_value': 'Employees must be at least 18 years old.'}, validators=[django.core.validators.MinValueValidator(18)])),
                ('hourly_wage', models.DecimalField(decimal_places=2, error_messages={'min_value': 'Hourly wage cannot be less than 0'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('hours_weekly', models.DecimalField(decimal_places=1, error_messages={'min_value': 'Working hours cannot be less than 0'}, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('hired_at', models.DateField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('assigned_bikes', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_bikes', to='garage.motorcyclemodel')),
                ('assigned_cars', models.ManyToManyField(blank=True, default=None, related_name='employees_cars', to='garage.carmodel')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
