# Generated by Django 6.0.2 on 2026-02-22 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('hours_weekly', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('hired_at', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('assigned_bikes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_bikes', to='garage.motorcyclemodel')),
                ('assigned_cars', models.ManyToManyField(blank=True, related_name='employees_cars', to='garage.carmodel')),
            ],
        ),
    ]
