# Generated by Django 6.0.2 on 2026-02-23 20:37

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Employees must be at least 18 years old.')]),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='first_name',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Hourly wage cannot be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='hours_weekly',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Working hours cannot be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='last_name',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
    ]
