# Generated by Django 6.0.2 on 2026-02-23 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeemodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='age',
            field=models.IntegerField(error_messages={'min_value': 'Employees must be at least 18 years old.'}, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, error_messages={'min_value': 'Hourly wage cannot be less than 0'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='hours_weekly',
            field=models.DecimalField(decimal_places=1, error_messages={'min_value': 'Working hours cannot be less than 0'}, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
