# Generated by Django 6.0.2 on 2026-03-22 22:01

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='generaluser',
            managers=[
                ('objects', accounts.managers.CustomGeneralUserManager()),
            ],
        ),
    ]
