# Generated by Django 6.0.2 on 2026-03-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_generaluser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluser',
            name='username',
        ),
    ]
