# Generated by Django 6.0.2 on 2026-02-23 20:57

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0, message='Price cannot be less than 0')]),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='title',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0, message='Price cannot be less than 0')]),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='title',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
    ]
