# Generated by Django 6.0.2 on 2026-03-22 18:46

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_partmodel_price_alter_partmodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='title',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alphanum]),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='title',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alphanum]),
        ),
    ]
