# Generated by Django 6.0.2 on 2026-02-23 15:37

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('mileage', models.BigIntegerField(validators=[common.validators.check_if_is_positive])),
                ('engine_displacement', models.DecimalField(decimal_places=1, max_digits=4, validators=[common.validators.check_if_is_positive])),
                ('horsepower', models.IntegerField(validators=[common.validators.check_if_is_positive])),
                ('fuel_type', models.CharField(choices=[('PET', 'Petrol'), ('DIESEL', 'Diesel')], max_length=20)),
                ('repair_status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('type', models.CharField(choices=[('MC', 'Motorcycle'), ('CAR', 'Car')], default='CAR', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('mileage', models.BigIntegerField(validators=[common.validators.check_if_is_positive])),
                ('engine_displacement', models.DecimalField(decimal_places=1, max_digits=4, validators=[common.validators.check_if_is_positive])),
                ('horsepower', models.IntegerField(validators=[common.validators.check_if_is_positive])),
                ('repair_status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('type', models.CharField(choices=[('MC', 'Motorcycle'), ('CAR', 'Car')], default='MC', editable=False, max_length=20)),
                ('engine_type', models.CharField(choices=[('2T', '2-Stroke'), ('4T', '4-Stroke')], max_length=15)),
                ('fuel_type', models.CharField(choices=[('PET', 'Petrol'), ('DIESEL', 'Diesel')], default='PET', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Motorcycle',
                'verbose_name_plural': 'Motorcycles',
            },
        ),
    ]
