# Generated by Django 6.0.2 on 2026-02-23 20:57

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='engine_displacement',
            field=models.DecimalField(decimal_places=1, error_messages={'min_value': 'Engine displacement cannot be less than 0'}, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='horsepower',
            field=models.IntegerField(error_messages={'min_value': 'Horsepower cannot be less than 0'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='mileage',
            field=models.BigIntegerField(error_messages={'min_value': 'Mileage cannot be less than 0'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='engine_displacement',
            field=models.DecimalField(decimal_places=1, error_messages={'min_value': 'Engine displacement cannot be less than 0'}, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='horsepower',
            field=models.IntegerField(error_messages={'min_value': 'Horsepower cannot be less than 0'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='make',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='mileage',
            field=models.BigIntegerField(error_messages={'min_value': 'Mileage cannot be less than 0'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='model',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alpha]),
        ),
    ]
