# Generated by Django 6.0.2 on 2026-02-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_carmodel_engine_displacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='make',
            field=models.CharField(max_length=50),
        ),
    ]
