# Generated by Django 6.0.2 on 2026-03-22 18:46

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_carmodel_make_alter_motorcyclemodel_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alphanum]),
        ),
        migrations.AlterField(
            model_name='motorcyclemodel',
            name='model',
            field=models.CharField(max_length=50, validators=[common.validators.check_if_is_alphanum]),
        ),
    ]
