# Generated by Django 6.0.2 on 2026-04-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.carmodel')),
                ('motorcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.motorcyclemodel')),
                ('parts', models.ManyToManyField(blank=True, to='catalogue.partmodel')),
                ('services', models.ManyToManyField(blank=True, to='catalogue.servicemodel')),
            ],
        ),
    ]
